package com.example.steamapp.ui.theme

import androidx.compose.ui.graphics.Color


val yellowish= Color(0xFFFFEE8C)

val primaryLight = Color(0xFF5C899D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4D7B8E)
val onPrimaryContainerLight = Color(0xFFFBFDFF)
val secondaryLight = Color(0xFF506169)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1E2EC)
val onSecondaryContainerLight = Color(0xFF54656D)
val tertiaryLight = Color(0xFF6D5277)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF876B91)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FB)
val onBackgroundLight = Color(0xFF1A1C1D)
val surfaceLight = Color(0xFFFFFCEF)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFDDE3E8)
val onSurfaceVariantLight = Color(0xFF41484C)
val outlineLight = Color(0xFF71787C)
val outlineVariantLight = Color(0xFFC1C7CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31302F)
val inverseOnSurfaceLight = Color(0xFFF4F0EE)
val inversePrimaryLight = Color(0xFF9FCDE3)
val surfaceDimLight = Color(0xFFDDD9D7)
val surfaceBrightLight = Color(0xFFFDF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F1)
val surfaceContainerLight = Color(0xFFF1EDEB)
val surfaceContainerHighLight = Color(0xFFEBE7E5)
val surfaceContainerHighestLight = Color(0xFFE5E2E0)

val primaryDark = Color(0xFF9FCDE3)
val onPrimaryDark = Color(0xFF003545)
val primaryContainerDark = Color(0xFF6A97AB)
val onPrimaryContainerDark = Color(0xFF001E29)
val secondaryDark = Color(0xFFB8C9D3)
val onSecondaryDark = Color(0xFF23333A)
val secondaryContainerDark = Color(0xFF3B4B53)
val onSecondaryContainerDark = Color(0xFFAABBC4)
val tertiaryDark = Color(0xFFDCBBE6)
val onTertiaryDark = Color(0xFF3F2749)
val tertiaryContainerDark = Color(0xFFA486AE)
val onTertiaryContainerDark = Color(0xFF281232)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111415)
val onBackgroundDark = Color(0xFFE2E2E4)
val surfaceDark = Color(0xFF141312)
val onSurfaceDark = Color(0xFFE5E2E0)
val surfaceVariantDark = Color(0xFF41484C)
val onSurfaceVariantDark = Color(0xFFC1C7CC)
val outlineDark = Color(0xFF8B9296)
val outlineVariantDark = Color(0xFF41484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E0)
val inverseOnSurfaceDark = Color(0xFF31302F)
val inversePrimaryDark = Color(0xFF366477)
val surfaceDimDark = Color(0xFF141312)
val surfaceBrightDark = Color(0xFF3A3938)
val surfaceContainerLowestDark = Color(0xFF0E0E0D)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A29)
val surfaceContainerHighestDark = Color(0xFF363533)